repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-docstring-first
    -   id: check-ast
    -   id: check-json
    -   id: pretty-format-json
        args: [--autofix, --indent, "4"]
    -   id: check-toml
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
-   repo: https://github.com/psf/black
    rev: '23.12.0'
    hooks:
      - id: black
        name: Check Python style and formatting
        language_version: python3.12
