[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "120"

[tool.isort]
profile = "black"
src_paths = ["advent_of_code"]

[tool.black]
line-length = 120
skip-string-normalization = true

