[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "120"

[tool.black]
line-length = 120
skip-string-normalization = true

[tool.coverage.report]
omit = ['*tests*']
